### ISSUE TITLE
能否支持一下，表名带特殊符号如$等的别名提示？

### ISSUE THREAD

**Issue by nixiaomei1205** [DTStack/dt-sql-parser#10]
我想请问下，遇到以下这种带${}的表名，可以支持下吗？

select data_days.xxx  from udap_test.TEST_ORACLE_FENBIAO${data_day} data_days;

感谢

**Comment by wewoor** [comment]
我们正在考虑支持，可以关注下

**Comment by wewoor** [comment]
@nixiaomei1205 请问你这个是哪种类型的 SQL
