### ISSUE TITLE
FlinkSQL  大小写敏感

### ISSUE THREAD

**Issue by mumiao** [DTStack/dt-sql-parser#107]
options { caseInsensitive = true; }

**Comment by HaydenOrz** [comment]
为什么需要显示的设置大小写敏感选项？

**Comment by mumiao** [comment]
> 为什么需要显示的设置大小写敏感选项？

来下我工位，我这边有演示下

**Comment by mumiao** [comment]
`options { caseInsensitive = true; }
`
配置项开启4.10版本，主要是兼容
![image](https://github.com/DTStack/dt-sql-parser/assets/22880945/438de463-d234-4d3c-9d69-9107da22b6ac)
大小写转换，会自动把`fragment LETTER: [A-Z];`转换成`fragment LETTER: [a-z];`
`

**Comment by HaydenOrz** [comment]
https://github.com/antlr/antlr4/blob/master/doc/options.md#caseinsensitive
