### ISSUE TITLE
Flink SQL  FILE_PATH 与 left/right 冲突

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-sql-parser#108]
+ 目前 `/ ` 两边如果没有空格，则 `/right` 会被识别为 FILE_PATH
![Image](https://github.com/DTStack/dt-sql-parser/assets/58289241/cc7944b0-0760-418a-b574-27be42a346e4)

+ 加上空格才能正确识别

![Image](https://github.com/DTStack/dt-sql-parser/assets/58289241/b697327b-6126-4034-8f30-8f25aaeae5dc)

**Comment by wewoor** [comment]
考虑添加 javascript 代码判断上下文做区分

**Comment by HaydenOrz** [comment]
Closed Via #112
