### ISSUE TITLE
支持 Auto-complete

### ISSUE THREAD

**Issue by wewoor** [DTStack/dt-sql-parser#13]
如下 SQL 类型：

- [ ] MySQL
- [x] Flink SQL
- [ ] Spark SQL
- [ ] Hive SQL
- [ ] PL/SQL

**Comment by melin** [comment]
有进展吗？

**Comment by melin** [comment]
期待早点有进展。。。

Ziv ***@***.***> 于2021年12月6日周一 20:03写道：

**Comment by wewoor** [comment]
> 

谢谢关注我们的项目

**Comment by wuhaohaoflake** [comment]
自动补全有进展吗？

**Comment by wewoor** [comment]
目前已经支持 FlinkSQL
