### ISSUE TITLE
Spark SQL syntax error

### ISSUE THREAD

**Issue by wewoor** [DTStack/dt-sql-parser#131]
![image](https://github.com/DTStack/dt-sql-parser/assets/2766811/eea107d5-3459-4d01-9c00-ddb52e473fb3)

Report from @zoudaokoulife

**Comment by liuxy0551** [comment]
completed by @OnlyFlyer

**Comment by liuxy0551** [comment]
completed by @OnlyFlyer   
https://github.com/DTStack/dt-sql-parser/pull/173/files#diff-d9f3b1ef273aa9ebbc9b903fa48845dbcaa7115cffb9c4c3f76cfff7958ef177R11
