### ISSUE TITLE
flink sql 语法文件中 unquotedIdentifier 只支持字母和数字问题

### ISSUE THREAD

**Issue by melin** [DTStack/dt-sql-parser#140]
flink sql 语法文件中 unquotedIdentifier 只支持字母和数字问题。set 语句 key 定义也引用了unquotedIdentifier。flink 参数中很多有横线，需要给参数添加上引号才可以使用，是否考虑unquotedIdentifier 支持横线？
<img width="856" alt="image" src="https://github.com/DTStack/dt-sql-parser/assets/1145830/301e2d54-042e-4bca-8c32-42a7a27481ac">

**Comment by HaydenOrz** [comment]
首先感谢你的反馈。

请问你是否有验证过，在不加引号的情况下，如果flinkSQL SET 语句的 key中带有 `-` 、`.` 等字符，sql 能否正常运行？如果你有验证结果，麻烦将你所使用的 flink 版本和验证结果告诉我们一下。

在 flink 官方文档中并没有详细描述 SET 语句的文法，这也是给我们造成困扰的原因之一。
![image](https://github.com/DTStack/dt-sql-parser/assets/58289241/b0ce073a-0c37-408e-86ee-6c2ad070c28b)


另外在 flink 官方文档中所有关于 SET 语句的示例，其中的 key 都是有引号包裹的，这最起码说明 flink 官方更推荐带有引号的写法。
![image](https://github.com/DTStack/dt-sql-parser/assets/58289241/782eb260-445c-4d5c-bdfd-7dae790a7e0e)
