### ISSUE TITLE
Check HiveSQL chore syntax

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-sql-parser#143]
### Refer Doc
https://cwiki.apache.org/confluence/display/Hive/LanguageManual

![Image](https://github.com/DTStack/monaco-sql-languages/assets/58289241/854fde82-489d-4992-94da-21b2fa80d4f4)

### Todo List
- [ ]  support missing syntax
- [ ]  correct incorrect syntax
- [ ]  unit tests

**Comment by mumiao** [comment]
@HaydenOrz HIVESQL  和 SPARKSQL  有跟引擎确认版本么，之前TRINOSQL 每个版本差异都比较大

**Comment by HaydenOrz** [comment]
Hive SQL 文档中废弃的语法会有记录有，所以直接按最新的文档来，
Spark SQL 还没有确认

目前只关心是否有废弃语法，现在的做法是按最新的来，并且兼容废弃语法
