### ISSUE TITLE
Check SparkSQL Auxiliary Syntax

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-sql-parser#149]
### Refer Doc
https://spark.apache.org/docs/latest/sql-ref-syntax.html#auxiliary-statements

![Image](https://github.com/DTStack/dt-sql-parser/assets/58289241/2762ffbb-6853-49dc-9e6a-9a405e87dd66)

### Todo List
- [ ] support missing syntax
- [ ] correct incorrect syntax
- [ ] unit tests

**Comment by OnlyFlyer** [comment]
https://github.com/DTStack/dt-sql-parser/pull/165
