### ISSUE TITLE
'SqlParserVisitor' (imported as 'SqlParserVisitor') was not found in 'dt-sql-parser'

### ISSUE THREAD

**Issue by hiliny** [DTStack/dt-sql-parser#153]
**The Type of SQL**
  mysql

**Your Code**
import { GenericSQL, SqlParserVisitor } from "dt-sql-parser";

**Problem**
export 'SqlParserVisitor' (imported as 'SqlParserVisitor') was not found in 'dt-sql-parser' (possible exports: FlinkSQL, GenericSQL, HiveSQL, PLSQL, PostgresSQL, SparkSQL, SyntaxContextType, cleanSql, lexer, splitSql)

notice that the SqlParserVisitor.js file is empty under dt-sql-parser/dist/lib/generic, is that normal?

**Comment by hiliny** [comment]
version is 4.0.0-beta.4.2

**Comment by HaydenOrz** [comment]
In fact, that is normal.

See [SqlParserVisitor file in src folder](https://github.com/DTStack/dt-sql-parser/blob/main/src/lib/generic/SqlParserVisitor.ts). This file is fully generated by antlr4ts, and it only exports one ts interface.  So when this file is compiled by tsc, it does not contain any exports.

You can use `SqlParserVisitor` in typescript by `implements`: 
```typescript
import { ErrorNode, ParseTree, RuleNode, TerminalNode } from "antlr4ts/tree";
import type { SqlParserVisitor } from "dt-sql-parser";
import { SelectStatementContext } from "dt-sql-parser/dist/lib/generic/SqlParser";

class MySqlParserVisitor implements SqlParserVisitor<any> {
    visit(tree: ParseTree) {
        // this method is required
    }
    visitChildren(node: RuleNode) {
        // this method is required
    }
    visitTerminal(node: TerminalNode) {
        // this method is required
    }
    visitErrorNode(node: ErrorNode) {
        // this method is required
    }
    visitSelectStatement?: (ctx: SelectStatementContext) => {
        // visit parserTreeContext ...
    };
}

export default MySqlParserVisitor;
```

or `extends AbstractParseTreeVisitor` directly
```typescript
import { AbstractParseTreeVisitor } from "antlr4ts/tree";
import type { SqlParserVisitor } from "dt-sql-parser";
import { SelectStatementContext } from "dt-sql-parser/dist/lib/generic/SqlParser";

class MySqlParserVisitor extends AbstractParseTreeVisitor<number> implements SqlParserVisitor<any> {
    protected defaultResult(): number {
        return null;
    }
    visitSelectStatement?: (ctx: SelectStatementContext) => {
        // visit parserTreeContext ...
    };
}

export default MySqlParserVisitor;
```
