### ISSUE TITLE
hive sql的validate不准确

### ISSUE THREAD

**Issue by 666doge** [DTStack/dt-sql-parser#16]
**The Type of SQL**

hive sql

**Your Code**

import {HiveSQL} from 'dt-sql-parser';

const parser = new HiveSQL();
const sqlStr = 'select * from abc from cc;';   // 错误的语法。
const errors = parser.validate(sqlStr);
console.log('errors:', errors);

**Problem**
没有打印出来错误信息

**Comment by wewoor** [comment]
@666doge 谢谢反馈，我们验证下，稍后会修复

**Comment by ProfBramble** [comment]
@666doge ，你好，我们经过排查，发现 hive 官方维护的语法解析文件 [grammar](https://github.com/apache/hive/blob/master/hplsql/src/main/antlr4/org/apache/hive/hplsql/Hplsql.g4#L1211) 所定义的表格名称（table_name）存在绑定关键字识别语法的行为，涉及的改动量比较大。

我们已记录下此问题，会安排进 dt-sql-parser 开发计划并进行修复

**Comment by mumiao** [comment]
![image](https://github.com/DTStack/dt-sql-parser/assets/22880945/31dc96c8-a575-4945-9103-a91e960ad5ad)

` 'select * from abc from cc;';`校验错误信息如图
