### ISSUE TITLE
flink-sql两种主要语法检验问题

### ISSUE THREAD

**Issue by easonliu30624700** [DTStack/dt-sql-parser#17]
**The Type of SQL**
e.g. Flink
1. INSERT OVERWRITE XXXX
2. LEFT JOIN  XXXX FOR SYSTEM_TIME AS OF XXXX
这两种语法校验不通过。能添加支持一下吗

**Comment by wewoor** [comment]
@easonliu30624700 待我们评估下，稍后版本应该会支持

**Comment by joelongLin** [comment]
insert overwrite 这个语法看起来还是没办法通过validate

**Comment by nankaNULL** [comment]
> insert overwrite 这个语法看起来还是没办法通过validate

感谢反馈，还请提供一下复现该问题的版本以及 sql 语句。

另，该问题我们已经在最新的 4.0.0-beta 版本中做了修复，后续我们将专注于 4.0 的开发，如若您在 3.x 上复现这个问题，请升级到最新版本。
