### ISSUE TITLE
SparkSqlLexer.js:42 Uncaught RangeError: Invalid code point -1

### ISSUE THREAD

**Issue by kouchao** [DTStack/dt-sql-parser#185]
**The Type of SQL**
```
// number + dot or dot + number
1.
```
**Your Code**
```
const sql = '1.'
const tree = parser.parse(sql);
```
**Problem**
![image](https://github.com/DTStack/dt-sql-parser/assets/23720738/54a394c7-d43f-48f7-9a15-660fc1018fb8)

**Comment by HaydenOrz** [comment]
麻烦提供一下安装的 `dt-sql-parser` 的版本

**Comment by kouchao** [comment]
> 麻烦提供一下安装的 `dt-sql-parser` 的版本

"dt-sql-parser": "^4.0.0-beta.4.2",

**Comment by HaydenOrz** [comment]
我们已经修复了此问题，将于近期发布新版本，新版本发布后，将会在此 issue 下同步发布信息。

**Comment by HaydenOrz** [comment]
dt-sql-parser `v4.0.0-beta.4.3` 版本已发布。
![image](https://github.com/DTStack/dt-sql-parser/assets/58289241/9c9f241c-3dda-43f5-a1b5-8492ac1ae97d)

现在你可以继续使用 `parse` 方法解析上面提到的 sql 内容，除此之外，你可以使用 `errorHandler ` 接收或处理语法错误，代码示例如下:

```javascript
import { SparkSQL } from 'dt-sql-parser';
const parser = new SparkSQL();
const errorHandler =(err) => {
    console.log(err);
}
const sql = '1.'
const tree = parser.parse(sql, errorHandler);
```
另外，非常感谢你的报告，如果后续使用过程中有任何问题，欢迎随时反馈。

**Comment by HaydenOrz** [comment]
如果你确定你的问题已经被解决，请关闭此 issue。
或者我们会在一周后关闭。

**Comment by kouchao** [comment]
已解决
