### ISSUE TITLE
Enhanced GenericSQL 

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-sql-parser#190]
## Todo List
+ [ ] 校正GenericSQL 语法文件，**参考MYSQL 官方文档**
+ [ ] 添加基础语法相关的单元测试， **所有支持的语法都要有单元测试用例**
+ [ ] 关键字的词法规则名称前加上 `KW_` 前缀
+ [ ] 梳理需要自动补全的语法规则，并优化对应的语法规则文件
+ [ ] GenericSQL 支持自动补全功能
+ [ ] GenericSQL 支持安语句切分SQL功能
+ [ ] GenericSQL 自动补全功能的单元测试

**Comment by liuxy0551** [comment]
已完成
