### ISSUE TITLE
Catalog 校验失败

### ISSUE THREAD

**Issue by kouchao** [DTStack/dt-sql-parser#200]
**Version**
v4.0.0-beta.4.3

**The Type of SQL**
SparkSQL

**Your Code**
```
parser.validate('
create table if not exists hive_prod.dev.henry_test_iceberg7 (
        test_id int
) using iceberg;
');
```

**Problem**
使用 `Catalog` 校验会出现错误
![企业微信截图_3fac87b3-6b6c-41cb-8712-95c18846889b](https://github.com/DTStack/dt-sql-parser/assets/23720738/b2496278-f5ae-4d5d-b662-07523707e7bd)

**Comment by HaydenOrz** [comment]
SparkSQL 目前并不支持 `Catalog` 相关语法，可以看一下官方文档
https://spark.apache.org/docs/latest/sql-ref-syntax.html
![image](https://github.com/DTStack/dt-sql-parser/assets/58289241/aaa9275e-cbfb-40c9-bdef-e72ef7639410)

**Comment by HaydenOrz** [comment]
> **Version** v4.0.0-beta.4.3
> 
> **The Type of SQL** SparkSQL
> 
> **Your Code**
> 
> ```
> parser.validate('
> create table if not exists hive_prod.dev.henry_test_iceberg7 (
>         test_id int
> ) using iceberg;
> ');
> ```
> 
> **Problem** 使用 `Catalog` 校验会出现错误 ![企业微信截图_3fac87b3-6b6c-41cb-8712-95c18846889b](https://user-images.githubusercontent.com/23720738/280171518-b2496278-f5ae-4d5d-b662-07523707e7bd.png)

如果使用的是其他的查询引擎比如 Trino 或者其他计算引擎比如 Flink，请考虑使用与之对应的 Parser

**Comment by phymo** [comment]
Version
4.1.0-beta.4

The Type of SQL
TrinoSQL

Is `using` keyword supported  when creating table in trino SQL?

![Image](https://github.com/user-attachments/assets/490cde77-76aa-4bfa-b0be-3551812e34a2)

**Comment by liuxy0551** [comment]
> Version 4.1.0-beta.4
> 
> The Type of SQL TrinoSQL
> 
> Is `using` keyword supported when creating table in trino SQL?
> 
> ![Image](https://github.com/user-attachments/assets/490cde77-76aa-4bfa-b0be-3551812e34a2)
> 
> [@HaydenOrz](https://github.com/HaydenOrz)



It seems that the `USING` keyword can not be used when creating a table in TrinoSQL. You should use WITH instead.
The syntax document: [https://trino.io/docs/current/sql/create-table.html#synopsis](https://trino.io/docs/current/sql/create-table.html#synopsis)

<img width="876" alt="Image" src="https://github.com/user-attachments/assets/ff1a427c-0164-4cf4-aeb3-53d66fb6808b" />
