### ISSUE TITLE
cleanSql 方法里逻辑是不是有问题

### ISSUE THREAD

**Issue by LeoMelody** [DTStack/dt-sql-parser#21]
/**
 * 清除注释和前后空格
 * @param {String} sql
 */
function cleanSql(sql: string) {
    sql.trim(); // 删除前后空格
    const tokens = lexer(sql);
    let resultSql = '';
    let startIndex = 0;
    tokens.forEach((ele: Token) => {
        if (ele.type === TokenType.Comment) {
            resultSql += sql.slice(startIndex, ele.start);
            startIndex = ele.end + 1;
        }
    });
    resultSql += sql.slice(startIndex);
    return resultSql;
}

上面删除前后空格这段代码并不会对源sql字段生效的。是不是要改成下面这样

/**
 * 清除注释和前后空格
 * @param {String} sql
 */
function cleanSql(origiSql: string) {
    let sql = origiSql.trim(); // 删除前后空格
    const tokens = lexer(sql);
    let resultSql = '';
    let startIndex = 0;
    tokens.forEach((ele: Token) => {
        if (ele.type === TokenType.Comment) {
            resultSql += sql.slice(startIndex, ele.start);
            startIndex = ele.end + 1;
        }
    });
    resultSql += sql.slice(startIndex);
    return resultSql;
}

**Comment by wewoor** [comment]
@LeoMelody 谢谢反馈
