### ISSUE TITLE
Can we add more rules (for Trino SQL) especially for supporting adding field completions?

### ISSUE THREAD

**Issue by Samrose-Ahmed** [DTStack/dt-sql-parser#211]
I see that Trino supports a few 'rules' , mostly function and table/view/catalog. Can we add more so we can e.g. differentiate between different contexts, e.g. I'm trying to add basic field autocomplete based on metadata, and adding field completions when the syntax context type is SyntaxContextType.FUNCTION but this causes it to conflict with e.g. when writing `select` (see image)

Also this may be separate (I opened a question in https://github.com/DTStack/monaco-sql-languages/discussions/77) but does function autocomplete for trino need to be added here or in the monaco-sql-languages package? Can open a separate issue if needed.

<img width="431" alt="Screenshot 2023-11-19 at 9 01 33 PM" src="https://github.com/DTStack/dt-sql-parser/assets/9027301/4702329a-6277-4865-9b87-3372b1a82dd4">

**Comment by HaydenOrz** [comment]
Regarding the auto-completion of fields, we have plans to support it. The main problem at the moment is that in the current context we can't get the table to which the field belongs.
For example, in the case of a SELECT statement, the FROM keyword can be very simple, such as a table
```sql
SELECT id, name FROM table1;
```
It can also be very complex, such as a subquery or a join clause
```sql
SELECT 
    id,
    name 
FROM
    SELECT * FROM  
        nation n CROSS JOIN region r;  
``` 

As a result, we can't accurately provide field codeCompletion items.

**Comment by Samrose-Ahmed** [comment]
Yes of course we're trying to add just basic field completion, without the table for now (i.e. suggest all tables fields). I understand why it wouldn't be built in as it gets very complicated.

I mean how can we differentiate between `sel` and `select col1, col` when doing our own completionService it seems to treat the two as the same.

**Comment by HaydenOrz** [comment]
The current problem is that you don't know when you should return a table column completion item in your completionService.   
We should indeed provide a SyntaxContextType that represents the tableColumn (i.e. `SyntaxContextType.COLUMN`).
