### ISSUE TITLE
lexer 函数死循环问题

### ISSUE THREAD

**Issue by LeoMelody** [DTStack/dt-sql-parser#22]
![image](https://user-images.githubusercontent.com/19320082/116093307-22fc3480-a6d9-11eb-8de7-51b3548edfbe.png)
这段代码有问题

如果是注释结尾这里就会陷入死循环。比如 
`let sql = 'select 1 --test';`

建议 `while (char !== '\n') ` 修改为 `while (char !== '\n' && current < input.length)  `

**Comment by wewoor** [comment]
@LeoMelody 谢谢反馈
