### ISSUE TITLE
export 'MySqlParserVisitor' (imported as 'MySqlParserVisitor') was not found in 'dt-sql-parser'

### ISSUE THREAD

**Issue by Landadadada** [DTStack/dt-sql-parser#236]
**Version**
4.0.0-beta.4.9

**The Type of SQL**
MySQL

**Your Code**
[从文档中复制的代码](https://github.com/DTStack/dt-sql-parser/blob/main/README-zh_CN.md#:~:text=...%0A%5D%0A*/-,%E8%AE%BF%E9%97%AE%E8%80%85%E6%A8%A1%E5%BC%8F%EF%BC%88Visitor%EF%BC%89,-%E4%BD%BF%E7%94%A8%20Visitor%20%E6%A8%A1%E5%BC%8F)

```js
import { MySQL, MySqlParserVisitor } from 'dt-sql-parser'

const parser = new MySQL()
const sql = 'select id,name from user1;'
// parseTree
const tree = parser.parse(sql)
class MyVisitor extends MySqlParserVisitor {
  // 重写 visitTableName 方法
  visitTableName(ctx) {
    let tableName = ctx.getText().toLowerCase()
    console.log('TableName', tableName)
  }

  // 重写 visitSelectElements 方法
  visitSelectElements(ctx) {
    let selectElements = ctx.getText().toLowerCase()
    console.log('SelectElements', selectElements)
  }
}
const visitor = new MyVisitor()
visitor.visit(tree)

```

**Problem**
从文档中复制的代码，在浏览器端运行报错，没有导出MySqlParserVisitor.  
为什么dist/lib/spark/SparkSqlParserVisitor.js导出的是空对象呢？

```
export 'MySqlParserVisitor' (imported as 'MySqlParserVisitor') was not found in 'dt-sql-parser' (possible exports: 
FlinkSQL, HiveSQL, ImpalaSQL, MySQL, PLSQL, PostgresSQL, SparkSQL, SyntaxContextType, TrinoSQL, legacy_cleanSql, legacy_lexer, legacy_splitSql)
```

**Comment by HaydenOrz** [comment]
>从文档中复制的代码，在浏览器端运行报错，没有导出MySqlParserVisitor.
为什么dist/lib/spark/SparkSqlParserVisitor.js导出的是空对象呢？

这是因为 MySqlParserVisitor 实际上是一个 typescript 的 interface， 经过 tsc 编译后类型被抹除了，如果你在非ts环境使用，则不需要 `extends MySqlParserVisitor`, 在功能上没有区别。

抱歉，文档上没有标注清楚，我会尽快在文档中说明。

**Comment by Landadadada** [comment]
请教：不继承MySqlParserVisitor的话，visit方法从哪里来呢？

**Comment by HaydenOrz** [comment]
> 请教：不继承MySqlParserVisitor的话，visit方法从哪里来呢？

@Landadadada  抱歉（再次），文档的代码示例太旧了，我刚刚没有注意到这个问题。`dt-sql-parser` 应该在入口文件导出抽象类 `AbstractParseTreeVisitor` ，但是现在没有导出，这是一个愚蠢且严重的问题，我会尽快修复这个问题并发布新版本。

**Comment by Landadadada** [comment]
```ts
import { MySQL, AbstractParseTreeVisitor } from 'dt-sql-parser';
import type { MySqlParserVisitor } from 'dt-sql-parser';

const parser = new MySQL();
const sql = `select id,name from user1;`;
const tree = parser.parse(sql);

type Result = string;

class MyVisitor extends AbstractParseTreeVisitor<Result> implements MySqlParserVisitor<Result> {
    protected defaultResult() {
        return '';
    }
    visitTableName(ctx) {
        let tableName = ctx.text.toLowerCase();
        console.log('TableName:', tableName);
        return '';
    }
    visitSelectElements(ctx) {
        let selectElements = ctx.text.toLowerCase();
        console.log('SelectElements:', selectElements);
        return '';
    }
    visitProgram(ctx) {
        return 'Return by program node'
    }
}
const visitor = new MyVisitor();
const result = visitor.visit(tree);

console.log(result);
```
文档中的vistor模式，本地运行，打印的结果只有`Return by program node`. 请问是否文档中的代码有遗漏呢？

**Comment by HaydenOrz** [comment]
> ```ts
> import { MySQL, AbstractParseTreeVisitor } from 'dt-sql-parser';
> import type { MySqlParserVisitor } from 'dt-sql-parser';
> 
> const parser = new MySQL();
> const sql = `select id,name from user1;`;
> const tree = parser.parse(sql);
> 
> type Result = string;
> 
> class MyVisitor extends AbstractParseTreeVisitor<Result> implements MySqlParserVisitor<Result> {
>     protected defaultResult() {
>         return '';
>     }
>     visitTableName(ctx) {
>         let tableName = ctx.text.toLowerCase();
>         console.log('TableName:', tableName);
>         return '';
>     }
>     visitSelectElements(ctx) {
>         let selectElements = ctx.text.toLowerCase();
>         console.log('SelectElements:', selectElements);
>         return '';
>     }
>     visitProgram(ctx) {
>         return 'Return by program node'
>     }
> }
> const visitor = new MyVisitor();
> const result = visitor.visit(tree);
> 
> console.log(result);
> ```
> 
> 文档中的vistor模式，本地运行，打印的结果只有`Return by program node`. 请问是否文档中的代码有遗漏呢？

好吧，示例代码中忘记了在 visitProgram 方法内部调用 `this.visitChildren(ctx);`

**Comment by Landadadada** [comment]
请教一下哦，最近在做sql解析相关的工作，想要深入了解如何使用dt-sql-parser里的方法进行sql解析，需要哪些前置知识呢？有没有其他的相关文档可供参考呢？ 感激不尽🙏

**Comment by HaydenOrz** [comment]
> 请教一下哦，最近在做sql解析相关的工作，想要深入了解如何使用dt-sql-parser里的方法进行sql解析，需要哪些前置知识呢？有没有其他的相关文档可供参考呢？ 感激不尽🙏

我不太了解你具体想要做哪些功能，如果你指的是应用 ANTLR4 生成的 `lexer`、`parser` 、`visitor` 和 `listener` 等，你可以参阅  [ANTLR4 doc](https://github.com/antlr/antlr4/tree/dev/doc)，或者你想要更深入的了解 ANTLR4 可以看 《ANTLR4 权威指南》 这本书。

另外，对于我来说，查看antlr4 运行时的源码中的注释也对我很有帮助，dt-sql-parser 使用的 ANTLR4 运行时是 [antlr4ts ](https://github.com/tunnelvisionlabs/antlr4ts) ，另外，还有另一个antlr4 的typescript 运行时 [antlr4ng](https://github.com/mike-lischke/antlr4ng)  也很棒。

**Comment by HaydenOrz** [comment]
@Landadadada  此问题将被关闭并锁定，后续有任何问题可以在 https://github.com/DTStack/dt-sql-parser/discussions/238 讨论
