### ISSUE TITLE
Have compiled js file download?

### ISSUE THREAD

**Issue by melin** [DTStack/dt-sql-parser#245]
能够提供编译后的js 文件下载，lei类似node-sql-parser 项目?

<img width="928" alt="image" src="https://github.com/DTStack/dt-sql-parser/assets/1145830/beb1539b-fc9c-4f55-b1b9-08986898b228">

**Comment by HaydenOrz** [comment]
抱歉，这暂时不在我们的计划之内，如果你需要的话，可以自行下载源码编译。
