### ISSUE TITLE
PgSQL  自动补全 一些场景下提示viewName

### ISSUE THREAD

**Issue by mumiao** [DTStack/dt-sql-parser#255]
https://github.com/DTStack/dt-sql-parser/issues/254

**Comment by HaydenOrz** [comment]
类型修改为 bug，此前在做这些sql时，多次强调需要注意 table 和 view，这个问题属于是做漏了

**Comment by Cythia828** [comment]
确实是没注意到，主要看它的语法结构了，就以语法结构为主了。后续像这种有争议的地方需要多去参考官方自己提供的示例来最终确定。
