### ISSUE TITLE
webpack production mod 下代码执行报错

### ISSUE THREAD

**Issue by wanglufei-567** [DTStack/dt-sql-parser#275]
我注意到你在antlr4ng提的issue
- https://github.com/mike-lischke/antlr4ng/issues/38
我遇到了和你同样的问题

请问dt-sql-parser@4.0.0-ng.1在production mod下应该如何构建可以避免antlr4ng执行报错的问题？

**Comment by wanglufei-567** [comment]
- https://github.com/mike-lischke/antlr4ng/pull/41

我注意到你给antlr4ng提的pr已经merged了，请问dt-sql-parser近期是否发布新版本来解决这个问题

**Comment by HaydenOrz** [comment]
> 我注意到你给antlr4ng提的pr已经merged了，请问dt-sql-parser近期是否发布新版本来解决这个问题

你可以安装  [0.12.0-beta.ng.2](https://www.npmjs.com/package/monaco-sql-languages/v/0.12.0-beta.ng.2) 版本，来修复此问题

**Comment by wanglufei-567** [comment]
> 你可以安装 [0.12.0-beta.ng.2](https://www.npmjs.com/package/monaco-sql-languages/v/0.12.0-beta.ng.2) 版本，来修复此问题
抱歉，我没有使用到monaco-sql-languages，因为我并没有使用monaco，所以dt-sql-parser近期是没有新版本发布计划是么

**Comment by HaydenOrz** [comment]
> 抱歉，我没有使用到monaco-sql-languages，因为我并没有使用monaco，所以dt-sql-parser近期是没有新版本发布计划是么

dt-sql-parser 也发布了 https://www.npmjs.com/package/dt-sql-parser/v/4.0.0-ng.2 版本。近期也会有发布计划，大概本周内发布。

**Comment by wanglufei-567** [comment]
好的，十分感谢

**Comment by HaydenOrz** [comment]
@wanglufei-567  已发布新版本 https://www.npmjs.com/package/dt-sql-parser/v/4.0.0-beta.4.12

**Comment by wanglufei-567** [comment]
> @wanglufei-567 已发布新版本 https://www.npmjs.com/package/dt-sql-parser/v/4.0.0-beta.4.12

get it
