### ISSUE TITLE
[Bug]: sql语句的from后面第一个应该是databse或者table

### ISSUE THREAD

**Issue by ouzhou** [DTStack/dt-sql-parser#284]
### Version

all

### Which SQL?

Hive

### SQL content

```sql
SELECT column1, column2, ...
FROM databaseName.tableName;
```

### JavaScript/TypeScript code

```typescript
import { FlinkSQL } from 'dt-sql-parser';

const flink = new FlinkSQL();
const sql = 'SELECT * FROM tb';
const pos = { lineNumber: 1, column: 16 }; // tb 的后面
const syntaxSuggestions = flink.getSuggestionAtCaretPosition(sql, pos)?.syntax;

console.log(syntaxSuggestions);
```

### What happened?

按官方案例来说，syntaxSuggestions应该返回 database table view
然后如果接下来有database.table 才是 table view

**Comment by HaydenOrz** [comment]
这是一个不好解决，也是一个见仁见智的问题，在这里已经有过类似的讨论 https://github.com/DTStack/dt-sql-parser/issues/189#issuecomment-1867405868

如果按你提到的这种情况下，返回 database 和 table，这在 hive 中没有任何问题。

但是在 Trino / Flink 中有三层结构（`catalog -> database -> table`）, 并且sql文本为 `SELECT * FROM a.b<插入位置>`，相应的应该返回 database 和 table，因为无法确定 a.b 是 `catalog.database` 还是 `database.table` 。这样的返回实际上显得有些奇怪，因为即使这样返回了，你仍然需要通过附带的 `wordRanges` 和 引擎真实的元数据信息结合来做一些判断。

目前dt-sql-parser 在处理这个问题时，不再考虑是否应该返回 database 或者 catalog，统一返回 table，开发者可以通过附带的 wordRanges 自行判断。这实际上也与许多文档中对语法的描述相对应，比如 [hive 的 query 文档](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Select)
![image](https://github.com/DTStack/dt-sql-parser/assets/58289241/ea5ee7c1-b10e-43c9-b8e8-b57c8ebb43e4)

另外，在hive 这种只有两层结构的sql语言中仍然保持只返回 table 的原因是，我们希望所有的 SQL 语言parser 的 API 的表现保持一致。

**Comment by ouzhou** [comment]
看了一下#189，目前是只支持拿本地上下文内craete的table进行补全吗？
如果是要做提前判断用户接下来要输入一个表名，使用从接口来的表名列表补全，应该如何实现？

**Comment by LuckyFBB** [comment]
> 看了一下#189，目前是只支持拿本地上下文内craete的table进行补全吗？ 如果是要做提前判断用户接下来要输入一个表名，使用从接口来的表名列表补全，应该如何实现？

目前支持使用接口来进行表名补全，你可以参考 [monaco-sql-languages](https://github.com/DTStack/monaco-sql-languages/blob/main/website/src/languages/helpers/completionService.ts#L15)的实现

![1](https://github.com/DTStack/dt-sql-parser/assets/38368040/d32de0c5-8b9d-4cd8-949c-3bf5e8d7dc2e)

**Comment by ouzhou** [comment]
<img width="800" alt="image" src="https://github.com/DTStack/dt-sql-parser/assets/7693866/afccac41-9c29-4900-b2d3-11551ef81a2c">

WHERE语句后面似乎不支持
