### ISSUE TITLE
[Bug]: 构建产物缺失

### ISSUE THREAD

**Issue by ouzhou** [DTStack/dt-sql-parser#285]
### Version

4.0.0-beta.4.12

### Which SQL?

MySQL

### What happened?

dist/lib/mysql/MySqlParserListener.js 

npm包文件打包缺失，MySqlParserListener.js是一个空盒子

```
// Generated from dt-sql-parser/src/grammar/mysql/MySqlParser.g4 by ANTLR 4.13.1
/**
 * This interface defines a complete listener for a parse tree produced by
 * `MySqlParser`.
 */
export class MySqlParserListener {
    visitTerminal(node) { }
    visitErrorNode(node) { }
    enterEveryRule(node) { }
    exitEveryRule(node) { }
}
```

**Comment by ouzhou** [comment]
<img width="948" alt="image" src="https://github.com/DTStack/dt-sql-parser/assets/7693866/f8a3bf5b-9a30-4484-a21c-d1b163650f4e">

**Comment by LuckyFBB** [comment]
这不是一个 bug。
dist/lib/mysql/MySqlParserListener.js 中的文件来源于 [MySqlParserListener](https://github.com/DTStack/dt-sql-parser/blob/v4.0.0-beta.4.12/src/lib/mysql/MySqlParserListener.ts)
对于这里面的每一个方法都需要重写实现某些方法，例如在 [MySqlEntityCollector](https://github.com/DTStack/dt-sql-parser/blob/v4.0.0-beta.4.12/src/parser/mysql/mysqlEntityCollector.ts) 实现 MySqlParserListener 具体实现某一些函数的具体内容

**Comment by ouzhou** [comment]
这个是官方给的示例，如何运行起来？

```
import { MySQL, MySqlParserListener } from 'dt-sql-parser';

const mysql = new MySQL();
const sql = 'select id, name from user1;';
const parseTree = mysql.parse(sql);

class MyListener extends MySqlParserListener {
    result = '';
    enterTableName = (ctx): void => {
        this.result = ctx.getText();
    };
}

const listener = new MyListener();
mysql.listen(listener, parseTree);

console.log(listener.result)
```

**Comment by ouzhou** [comment]
@LuckyFBB 搞清楚了，这是一个文档问题，这里应该是implements而不是extend，但是用定义类的方式有点奇怪，感觉直接传一个对象进去更符合常规使用习惯?

**Comment by HaydenOrz** [comment]
> @LuckyFBB 搞清楚了，这是一个文档问题，这里应该是implements而不是extend，但是用定义类的方式有点奇怪，感觉直接传一个对象进去更符合常规使用习惯?

这不是一个文档问题，dt-sql-parser 导出的 MySqlParserListener 是一个类，从语义上看，应该使用 extends 关键字，这算是一个 bug。

dt-sql-parser 最近切换了 antlr4 运行时（从 antlr4ts 切换到 antlr4ng），在antlr4ts 中 antlr4ts-cli 生成的 visitor和listener 都是 interface，所以此前文档中使用的是 implements 关键字来实现 visitor 和 listener，入口文件也仅将其当作类型导出。

在切换了运行时到 antlr4ng 后，antlr4ng-cli 生成的 visitor 和 listener 都是 class， 因此文档更新为使用 extends 关键字来继承 visitor 和 listener，但是没有注意到 dt-sql-parser 的入口文件仅将其当作类型导出，我们会尽快修复此问题。


> 顺带问一下enterTableName这个函数有文档吗？

你可以通过继承SQL 类型对应的  visitor 和 listener  在编辑器中得到对应的 typescript 的自动提示。除此之外没有文档。这主要是因为这些 visitor 和 listener 都是 antlr4 根据 g4 文件中的规则自动生成的，内部带有大量的方法类型定义，很难对它编写文档。 也因此，我们无法保证在后续更新的过程中不会对 visitor 和 listener 内部的方法造成破坏性变更。


antlr4 listener 相关的文档可以看
1. https://github.com/antlr/antlr4/blob/dev/doc/listeners.md
