### ISSUE TITLE
[Feature Request]: 如何实现自动提示字段？

### ISSUE THREAD

**Issue by ouzhou** [DTStack/dt-sql-parser#287]
### Topic

Enhance existing features

### Description

想实现自动提示字段名，当光标在cursor的位置的时候，希望提示test_table的字段

尝试使用listener实现，但是经过测试listener的enterTableName并不能分辨出当前处于哪一条语句的table，有最佳实践吗？

```
SELECT <cursor> FROM test_table1;SELECT a FROM test_table2;
```

**Comment by ouzhou** [comment]
看了一篇[文章](https://github.com/ascoders/weekly/blob/master/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/85.%E7%B2%BE%E8%AF%BB%E3%80%8A%E6%89%8B%E5%86%99%20SQL%20%E7%BC%96%E8%AF%91%E5%99%A8%20-%20%E6%99%BA%E8%83%BD%E6%8F%90%E7%A4%BA%E3%80%8B.md)

大概实现类似这样的函数的功能

```
monacoSqlAutocomplete(monaco, editor, {
  onInputTableField: async tableName => { // ...},
  onInputTableName: async () => { // ... },
  onInputFunctionName: async () => { // ... },
  onHoverTableName: async cursorInfo => { // ... },
  onHoverTableField: (fieldName, extra) => { // ... },
  onHoverFunctionName: functionName => { // ... }
});
```

**Comment by HaydenOrz** [comment]
https://github.com/DTStack/dt-sql-parser/blob/main/README-zh_CN.md#%E8%8E%B7%E5%8F%96-sql-%E4%B8%AD%E5%87%BA%E7%8E%B0%E7%9A%84%E5%AE%9E%E4%BD%93%E8%A1%A8%E5%90%8D%E5%AD%97%E6%AE%B5%E5%90%8D%E7%AD%89

**Comment by ouzhou** [comment]
我试过这个，目前的问题是并不能分辨出当前处于哪一条语句的table
当存在多个table的时候，我其实只想提示当前正在的这条语句
比如下面这个，我只想提示test_table1的字段
SELECT <cursor> FROM test_table1;SELECT a FROM test_table2;

**Comment by HaydenOrz** [comment]
![image](https://github.com/DTStack/dt-sql-parser/assets/58289241/a1527bf4-d229-4535-b2ec-76b4df473a80)
