### ISSUE TITLE
[Bug]: webpack mode=production模式下，文件访问报错

### ISSUE THREAD

**Issue by MyMaNong** [DTStack/dt-sql-parser#300]
### Version

4.0.0-beta.4.15

### Which SQL?

MySQL

### What happened?

mysql.worker.js  build后访问报错：Cannot read properties of null (reading "0").   报错位置：readInt方法 this.data为null

**Comment by liuxy0551** [comment]
可以参考下：https://github.com/DTStack/monaco-sql-languages/issues/98

**Comment by liuxy0551** [comment]
我们内部基于 webpack5 的打包工具是这样解决的，可以参考下：https://github.com/DTStack/ko/issues/163
