### ISSUE TITLE
[Bug]: ctxToWord is a bad function 

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-sql-parser#305]
### Version

v4.0.1

### Which SQL?

Any Others

### What happened?

某些情况下，ctxToWord 方法无法表达实体的位置，比如
```sql
SELECT * FROM a
.b
.c;
```

**Comment by Cythia828** [comment]
https://github.com/DTStack/dt-sql-parser/pull/319

**Comment by Cythia828** [comment]
已修复，ctxToText替换了原来的ctxToWord方法，表达了准确的位置信息「例如描述中换行的情况」
