### ISSUE TITLE
[Bug]: "ALTER TABLE" can collect entities but entities don't have belongStmt

### ISSUE THREAD

**Issue by Kijin-Seija** [DTStack/dt-sql-parser#311]
### Version

4.0.1

### Which SQL?

Postgre

### SQL content

```sql
ALTER TABLE my_table DROP a_column|;
```

### What happened?

`my_table` can be collected but it has no `belongStmt`, then people cannot use `isContainCaret` or other properities

---

`my_table`被收集了但是其属性里没有`belongStmt`, 基于`isContainCaret`或其他StmtContext属性的功能可能会无法正常工作。

![image](https://github.com/DTStack/dt-sql-parser/assets/27846243/cce9787d-f3f2-47c7-acf9-fab870d3b4aa)

I find that maybe there's no definition of `altertablestmt`. I will create a PR and try to cover it. If there is already a roadmap, ignore the PR.

---

看了下好像是没有定义'altertablestmt'这个StmtContext，我这边尝试添加了一下，已测试通过。如果这在你们的roadmap上，请忽略此PR

**Comment by HaydenOrz** [comment]
此issue先关闭，实体收集相关问题请追踪 https://github.com/DTStack/dt-sql-parser/issues/325
