### ISSUE TITLE
正确的FlinkSQL函数语句会标红色的错误

### ISSUE THREAD

**Issue by yly1207** [DTStack/dt-sql-parser#329]
![image](https://github.com/DTStack/monaco-sql-languages/assets/82200570/4cf80516-7376-4950-863c-f9789c2e5488)

**Comment by Cythia828** [comment]
![image](https://github.com/DTStack/dt-sql-parser/assets/21350892/ac6da8ce-3d67-4844-b69d-a730e19c67c5)


字段为数组时也飘红
