### ISSUE TITLE
[Bug]: postgreSQL syntax error

### ISSUE THREAD

**Issue by Cythia828** [DTStack/dt-sql-parser#339]
### Version

lasted

### Which SQL?

Postgre

### SQL content

```sql
CREATE TABLE distributors (
    did     integer,
    name    varchar(40),
    CONSTRAINT con1 CHECK (did > 100 AND name <> '')
);
```

### What happened?

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/50ab5dab-4694-44b5-a155-8ea36b3c1471">
<img width="1367" alt="image" src="https://github.com/user-attachments/assets/70845e2f-c37e-45aa-a240-1f6a905b2e76">

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/567095a2-4fbc-4527-ae6f-1666f6897756">
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/4ed3bea0-3793-420b-8988-4e1dbeb0e54d">

- 从前三个图可以看出，`CREATE TABLE`语句中的字段在`CONSTRAINT`情况下字段名是非必填的，但是明显我们不填也不报错，甚至把`CONSTRAINT`解析为字段名了，说明语法上有点问题
- 从第四个图可以看出`SELECT`语句中将本应是字段的地方解析为了`function_name`了，目前我们基本都没收集`function_name`在各类语句使用的形态，但是一旦我们开启要收集、提示`function_name`就会出现实体收集错误的情况

**Comment by mumiao** [comment]
done with https://github.com/DTStack/dt-sql-parser/pull/359

**Comment by liuxy0551** [comment]
The issue has been resolved in `dt-sql-parser@4.1.0-beta.3`.
