### ISSUE TITLE
[Bug]: HiveSQL 校验错误

### ISSUE THREAD

**Issue by DevilCyd** [DTStack/dt-sql-parser#350]
### Version

v4.1.0-beta.0

### Which SQL?

Hive

### SQL content

```sql
set hive.xx.select.result.encode.enabled=true;
```

### What happened?

![hive](https://github.com/user-attachments/assets/3a953c1e-5733-4470-b4fa-e73c88a9eabf)

**Comment by mumiao** [comment]
done with  https://github.com/DTStack/dt-sql-parser/pull/365

**Comment by liuxy0551** [comment]
The issue has been resolved in `dt-sql-parser@4.1.0-beta.3`.
