### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by DevilCyd** [DTStack/dt-sql-parser#353]
请问 我现在如何降低HiveSQL、SparkSQL的版本呢？

**Comment by liuxy0551** [comment]
无法简单快速的降低 SparkSQL 和 HiveSQL 的版本。

因为这些语法规则都写在 `src/grammar` 文件夹下的 g4 文件中，并没有细致的区分哪一条规则是某个版本的语法规则；不过一般高版本都会兼容低版本的语法，也就是说一般低版本的语法在高版本中并不会出现解析错误。

如果你遇到了语法版本问题，可以提供下具体的 SQL 语句一起分析下。

**Comment by DevilCyd** [comment]
SELECT
    a.p_month AS "账期" 
比如这种as 中文 就会标错。
![aacf3e86-7530-4796-9f1e-e4b5750bc29a](https://github.com/user-attachments/assets/bbc27eb9-c835-43ca-9cb3-d0744cade3df)

**Comment by liuxy0551** [comment]
SparkSQL 中别名这里使用双引号不会报错
<img width="476" alt="image" src="https://github.com/user-attachments/assets/29643048-be0c-4c75-91aa-03f4103642e3">

HiveSQL 中别名这里应当使用反引号
<img width="473" alt="image" src="https://github.com/user-attachments/assets/4bea2bc1-fc04-498e-8002-91b42f879b8c">

依据：[hive.support.quoted.identifiers](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=27842758#ConfigurationProperties-hive.support.quoted.identifiers)
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/285894f9-ac56-476f-a657-6bfe0690593a">
<img width="1527" alt="image" src="https://github.com/user-attachments/assets/6ca994b0-8765-4e1b-81dd-7fe33d0bc377">

**Comment by DevilCyd** [comment]
你好 这种呢？如果也是官网规范的话 我针对这种异常 要通过什么关键字 才能在官网查到相关规则呢？
![image](https://github.com/user-attachments/assets/4a521ffb-c0df-4fde-aa51-790c9d7f2408)

**Comment by DevilCyd** [comment]
有些我理解是不是可以归类到warn里边 我看输出的信息里没有分类。

**Comment by liuxy0551** [comment]
> 有些我理解是不是可以归类到warn里边 我看输出的信息里没有分类。

目前没有做分类，都是归类到语法错误中了

**Comment by liuxy0551** [comment]
> 你好 这种呢？如果也是官网规范的话 我针对这种异常 要通过什么关键字 才能在官网查到相关规则呢？ ![image](https://private-user-images.githubusercontent.com/20756954/370977342-4a521ffb-c0df-4fde-aa51-790c9d7f2408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjMzMTMsIm5iZiI6MTcyNzMyMzAxMywicGF0aCI6Ii8yMDc1Njk1NC8zNzA5NzczNDItNGE1MjFmZmItYzBkZi00ZmRlLWFhNTEtNzkwYzlkN2YyNDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAzNTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZjFjMjViODQ4ZDZkZTJmZWRlN2U2NzA3NzRjYjVjNDJjYzBjN2UwNDc1Njc3MjFhNmQ0YjI3OGU5ZWE2NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.loxTvDY_sCdzzYRc1NS7uYiKOVSEmOofspB_x_mXg7Q)

排查发现是 HiveSQL 中 `LEFT` 关键字的原因导致匹配到的规则错误，晚点修复。用到的复现 SQL 是：

``` sql
SELECT
    LEFT (cal, 1) AS a,
    SUM(cnt) / COUNT(DISTINCT cal) AS b
FROM
    t1;
```

**Comment by liuxy0551** [comment]
**类似问题可以先执行 SQL 语句确认是否能够执行，再检查语法飘红问题**

检查发现 HiveSQL 并不支持 `LEFT` 函数，SparkSQL 支持，HiveSQL 中可以考虑 `substr` 等函数。

``` sql
SELECT substr('Hello World', 0, 4);
```

<img width="1783" alt="image" src="https://github.com/user-attachments/assets/43fb2deb-b331-4240-8aca-ae20c6f5dcea">


HiveSQL 函数列表：https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-Built-inFunctions
SparkSQL 函数列表：https://spark.apache.org/docs/3.5.1/sql-ref-functions-builtin.html#string-functions

**Comment by DevilCyd** [comment]
收到 感谢。

**Comment by DevilCyd** [comment]
SparkSQL解析：

<img width="688" alt="image" src="https://github.com/user-attachments/assets/13a00460-483b-4eba-9a59-9c8c690deca2">

select * form app.liu_txxx_old; --多负责人

select * forrrrrrm dim.test_wqxxxxx_sc_20240521_001; --无权限

select * form app_dev.test_dqxxxxx_renling;;;;;

这种是什么原因呢？标到了关键字的后边

**Comment by liuxy0551** [comment]
> SparkSQL解析：
> 
> <img alt="image" width="688" src="https://private-user-images.githubusercontent.com/20756954/371077803-13a00460-483b-4eba-9a59-9c8c690deca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQxNTYsIm5iZiI6MTcyNzM0Mzg1NiwicGF0aCI6Ii8yMDc1Njk1NC8zNzEwNzc4MDMtMTNhMDA0NjAtNDgzYi00ZWJhLTlhNTktOWM4YzY5MGRlY2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMGRlNDllY2YxMWI4OTUxYmE3N2RiZDQ0ZjM2MTZkYmI0NDBhNWRkNGZhYjc4ZWY0YTBlNzY3NGM5MDFjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0DEL6c227-VO9ZebM59-tWFkKlJPNHxhYbLvZ9zZxvA">
> select * form app.liu_txxx_old; --多负责人
> 
> select * forrrrrrm dim.test_wqxxxxx_sc_20240521_001; --无权限
> 
> select * form app_dev.test_dqxxxxx_renling;;;;;
> 
> 这种是什么原因呢？标到了关键字的后边



`form` 识别为了 columnAlias，和你刚刚微信私聊的问题是一样的，这样也可以写别名。
<img width="988" alt="image" src="https://github.com/user-attachments/assets/14bfdd28-4ed3-4e83-af62-faa6b5f8600c">
