### ISSUE TITLE
[Bug]: hivesql 校验错误

### ISSUE THREAD

**Issue by lipengpeng288** [DTStack/dt-sql-parser#362]
### Version

v4.0.2

### Which SQL?

Hive

### SQL content

```sql
set hiveVar:A=1
```

### What happened?

语法校验错误： mismatched input ':' expecting {'.',EQUAL}
期待：校验通过

**Comment by liuxy0551** [comment]
```
SET hivevar:A = 1;
SELECT ${A};
SELECT ${hivevar:A};
```

**Comment by mumiao** [comment]
done with https://github.com/DTStack/dt-sql-parser/commit/c232aaa0eb974e8f9c7d36440fea13b79a38bbfd
