### ISSUE TITLE
请问最新版的别名自动提示获取方法是什么？

### ISSUE THREAD

**Issue by nixiaomei1205** [DTStack/dt-sql-parser#49]
**The Type of SQL**
select t2. from tablea t2;

**Your Code**
import { parser} from 'dt-sql-parser'
parser.parserSql(['select t2.', ' from tablea t2'], 'impala');

**Problem**
parser is undefined

**Comment by nixiaomei1205** [comment]
现在的版本没有自动补全方法了吗？

**Comment by wewoor** [comment]
> 现在的版本没有自动补全方法了吗？

是的，4.0 版本重点是支持多种不同类型的 SQLParser,
