### ISSUE TITLE
有些sql分割出来有问题

### ISSUE THREAD

**Issue by 2724635499** [DTStack/dt-sql-parser#71]
![image](https://user-images.githubusercontent.com/16345575/215314614-7cfba676-7786-4454-8709-ee3113c3dd4b.png)
![image](https://user-images.githubusercontent.com/16345575/215314630-6d9609e7-222a-4827-8dec-eec8cdb8a1f8.png)

**Comment by HaydenOrz** [comment]
Now, use `parser.splitSQLByStatement` to replace the legacy utils. For detail see [doc ](https://github.com/DTStack/dt-sql-parser#splitting-sql-statements)
