### ISSUE TITLE
请更新一下所依赖的antlr4的版本

### ISSUE THREAD

**Issue by kagaricyan** [DTStack/dt-sql-parser#74]
**The Type of SQL**
无

**Your Code**
无

**Problem**
目前引用的antlr4@4.7.2里面 package.json  `main`  字段指向的文件不存在，vite会报错

**Comment by carotte-tomato** [comment]
same problem, antlr4 has resolved this [issue](https://github.com/antlr/antlr4/issues/3917#issuecomment-1267501934)

**Comment by HaydenOrz** [comment]
已经将antlr4 运行时库从 antlr4 替换为 antlr4ts
