### ISSUE TITLE
Complete the FlinkSQL Grammar, Add more unit tests

### ISSUE THREAD

**Issue by wewoor** [DTStack/dt-sql-parser#78]

**Comment by wewoor** [comment]
> Hi, wewoor,
> 
> 我对你们的开源项目非常感兴趣，我想知道你们开发的FlinkSQL Parser预计什么时候会发布新版本到npm？https://www.npmjs.com/package/dt-sql-parser 我注意到到上一次你们的发布已经是5个月之前。你们 FlinkSQL Parser 的工程非常出色，非常期待你们能够发布新版！ 😉

近期应该就会发布的 0.0

**Comment by HaydenOrz** [comment]
FlinkSQL parser 目前已支持，请安装最新版 `dt-sql-parser` ，如果在使用过程中有任何问题，欢迎随时反馈。
