### ISSUE TITLE
Check Data Types

### ISSUE THREAD

**Issue by wewoor** [DTStack/dt-sql-parser#96]

**Comment by mumiao** [comment]
我会参考https://help.aliyun.com/apsara/enterprise/v_3_13_0_20201215/oceanbase/enterprise-user-guide/interval-day-to-second-data-type.html结合FlinkSQL官方文档一起去完善掉DataType, columnType 以及其他很多类型都直接用DataType约束，已经确认过。

**Comment by mumiao** [comment]
![image](https://github.com/DTStack/dt-sql-parser/assets/22880945/9e9be628-15b3-4d65-b5f5-ffab5e55a453)

用户可以自定义类型，这个关于`type`，要不要放在`grammar`需要讨论
