### ISSUE TITLE
flink sql grammar 文件 rule 命名规范

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-sql-parser#97]
主要是指后缀，比如
+ xxxClause
+ xxxStatement
+ xxxSpec
+ xxxDefination

可以参考flink sql 官方文档描述中的用词和 [grammars-v4](https://github.com/antlr/grammars-v4) 仓库

**Comment by mumiao** [comment]
#99 这两个一起的，标记也是跟着rule命名拼起来的
